export const UNAUTHORIZED = 'UNAUTHORIZED';
export const SIGNIN_NO_USER = 'SIGNIN_NO_USER';
export const SIGNIN_WRONG_PASSWORD = 'SIGNIN_WRONG_PASSWORD';
export const SIGNIN_MISSNG_PASSWORD = 'SIGNIN_MISSNG_PASSWORD';
